services:

  loki2slack:
    image: ghcr.io/helix-collective
    volumes:
      - ./loki2slack.cfg:/config/loki2slack.cfg
      # - ./cfg.json:/config/loki2slack.cfg
      - ./template_sample_02/template_with_attachment.tmpl:/config/template.tmpl
    command: --logtostderr tail -c /config/loki2slack.cfg

  tails:
    image: ghcr.io/helix-collective
    volumes:
      - ./tails.cfg:/config/tails.cfg
      - ./template_with_attachment.tmpl:/config/template_with_attachment.tmpl
      - ./template_without_attachment.tmpl:/config/template_without_attachment.tmpl
    command: --logtostderr tails -c /config/tails.cfg

  loki:
    image: grafana/loki:2.2.1
    ports:
      - "3100:3100"
      - "9096:9096"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:8.0.4
    ports:
      - "3000:3000"
  
  # TODO create a service which logs to loki