services:

  loki2slack:
    image: ghcr.io/helix-collective
    volumes:
      - ./cfg.json:/config/loki2slack.cfg
      - ./template_sample_01/msg_template.tmpl:/config/msg_template.tmpl
      - ./template_sample_01/att_template.tmpl:/config/att_template.tmpl
    command: --logtostderr tail -c /config/loki2slack.cfg

  loki:
    image: grafana/loki:2.2.1
    ports:
      - "3100:3100"
      - "9096:9096"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:8.0.4
    ports:
      - "3000:3000"
  
  # TODO create a service which logs to loki